# Generated by Django 5.1.3 on 2025-03-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.UUIDField(primary_key=True, serialize=False)),
                ('prompt', models.CharField(max_length=4000)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
