# Generated by Django 5.1.3 on 2025-03-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_generator', '0002_alter_image_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='size',
            field=models.CharField(default='', max_length=20),
        ),
    ]
