# Generated by Django 5.1.3 on 2025-04-14 18:15

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_generator', '0003_image_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536, null=True),
        ),
    ]
